---
- name: Install code-server
  shell: curl -fsSL https://code-server.dev/install.sh | sh
  args:
    chdir: /home/{{ username }}
  become: true
  become_user: "{{ username }}"

- name: Enable and start code-server service
  systemd:
    name: "code-server@{{ username }}"
    enabled: yes
    state: started
  become: true

- name: Ensure code-server configuration is set
  lineinfile:
    path: /home/{{ username }}/.config/code-server/config.yaml
    create: yes
    line: "{{ item }}"
  loop:
    - "bind-addr: {{ ansible_default_ipv4.address }}:8080"
    - "auth: none"
    - "cert: false"
  become: true
  become_user: "{{ username }}"

- name: Install code-server extensions
  shell: code-server --install-extension {{ item }}
  loop: "{{ code-server_extensions }}"
  become: true
  become_user: "{{ username }}"