---
- name: Create scripts and appdata directories in the current user's home directory
  file:
    path: "/home/{{ username }}/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - scripts
    - appdata