    - name: Get the latest Fira Code Nerd Font release URL
      ansible.builtin.shell: |
        curl -s https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest | jq -r '.assets[] | select(.name | contains("FiraCode.zip")) | .browser_download_url'
      register: fira_code_download_url
      failed_when: fira_code_download_url.stdout == ""

    - name: Debug the download URL (optional)
      ansible.builtin.debug:
        msg: "Fira Code Nerd Font Download URL: {{ fira_code_download_url.stdout }}"

    - name: Download the latest Fira Code Nerd Font
      get_url:
        url: "{{ fira_code_download_url.stdout }}"
        dest: /tmp/FiraCode.zip

    - name: Extract Fira Code Nerd Font
      unarchive:
        src: /tmp/FiraCode.zip
        dest: /usr/share/fonts
        remote_src: yes

    - name: Refresh font cache
      ansible.builtin.command:
        cmd: fc-cache -fv