---
- name: Ensure Zsh with dependencies are installed
  apt:
    name: "zsh"
    state: present
    update_cache: yes

- name: Ensure zsh is the default shell
  user:
    name: "{{ username }}"
    shell: "/usr/bin/zsh"

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
  register: oh_my_zsh_install

- name: Display Oh My Zsh installation messages
  debug:
    msg: "{{ oh_my_zsh_install.stdout }}"
    
#- name: Ensure Oh My Zsh plugins directory exists
#  file:
#    path: "/home/{{ username }}/.oh-my-zsh/custom/plugins"
#    state: directory
#    owner: "{{ username }}"
#    group: "{{ username }}"

- name: Install Zsh plugins if not already installed
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
    update: no
  loop: "{{ zsh_plugins }}"
  register: zsh_plugins_result

#- name: Refresh Zsh plugin directory ownership
#  file:
#    path: "/home/{{ username }}/.oh-my-zsh/custom/plugins"
#    recurse: yes
#    owner: "{{ username }}"
#    group: "{{ username }}"