---
- name: Ensure Zsh with dependencies are installed
  apt:
    name: "zsh"
    state: present
    update_cache: yes
  become: true
  become_user: "{{ username }}"

- name: Ensure zsh is the default shell
  user:
    name: "{{ username }}"
    shell: "/usr/bin/zsh"
  become: true
  become_user: "{{ username }}"

- name: Download Oh My Zsh installation script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh
  become: true
  become_user: "{{ username }}"

- name: Run Oh My Zsh installation script
  command: sh /tmp/install_ohmyzsh.sh --unattended
  register: ohmyzsh_result
  failed_when: "'FAILED' in ohmyzsh_result.stderr"
  become: true
  become_user: "{{ username }}"

- name: Check if zsh-syntax-highlighting directory exists
  stat:
    path: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  register: zsh_syntax_highlighting_installed
  become: true
  become_user: "{{ username }}"

- name: Install zsh-syntax-highlighting when not already installed
  shell: |
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  when: not zsh_syntax_highlighting_installed.stat.exists
  become: true
  become_user: "{{ username }}"

- name: Check if the zsh-autosuggestions directory exists
  stat:
    path: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  register: zsh_autosuggestions_installed
  become: true
  become_user: "{{ username }}"


- name: Install zsh-autosuggestions when not already installed
  shell: |
    git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  when: not zsh_autosuggestions_installed.stat.exists
  become: true
  become_user: "{{ username }}"