---
- name: Check if chezmoi is already installed
  stat:
    path: /home/{{ username }}/.local/bin/chezmoi
  register: chezmoi_installed

- name: Download chezmoi install script
  get_url:
    url: https://get.chezmoi.io
    dest: /tmp/install_chezmoi.sh
    mode: '0755'
  when: not chezmoi_installed.stat.exists

- name: Run Chezmoi installation script
  shell: /tmp/install_chezmoi.sh -b /home/{{ username }}/.local/bin
  args:
    creates: "/home/{{ username }}.local/bin/chezmoi"
  when: not chezmoi_installed.stat.exists

- name: Initialize and apply chezmoi
  shell: |
    chezmoi init --apply {{ github_username }}
  args:
    chdir: "/home/{{ username }}"

- name: Remove Chezmoi installation script
  ansible.builtin.file:
    path: /tmp/install_chezmoi.sh
    state: absent