- name: Check if chezmoi is already installed
  stat:
    path: /home/{{ username }}/.local/bin
  register: chezmoi_installed

- name: Install chezmoi 
  shell: |
    sh -c "$(curl -fsLS get.chezmoi.io/lb)" -- init --apply augerl
  when: not chezmoi_installed.stat.exists