---
- name: Install and apply Chezmoi with GitHub username
  ansible.builtin.shell:
    cmd: 'sh -c "$(curl -fsLS get.chezmoi.io/lb)" -- init --apply {{ github_username }}'
  environment:
    HOME: "/home/{{ username }}"
  args:
    chdir: "/home/{{ username }}"