- name: Check if chezmoi is already installed
  stat:
    path: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  register: chezmoi_installed
  become: true
  become_user: "{{ username }}"

- name: Install zsh-autosuggestions when not already installed
  shell: |
    sh -c "$(curl -fsLS get.chezmoi.io/lb)" -- init --apply {{ github-user }}
  when: not chezmoi_installed.stat.exists
  become: true
  become_user: "{{ username }}"