---
- name: Check if Chezmoi is already installed
  ansible.builtin.stat:
    path: "/home/{{ username }}/.local/bin/chezmoi"
  register: chezmoi_exists

- name: Install and apply Chezmoi with GitHub username
  ansible.builtin.shell:
    cmd: 'sh -c "$(curl -fsLS get.chezmoi.io/lb)" -- init --apply {{ github_username }}'
  environment:
    HOME: "/home/{{ username }}"
  args:
    chdir: "/home/{{ username }}"
  when: not chezmoi_exists.stat.exists

- name: Clone the tmux plugin manager repository
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/{{ username }}/.config/tmux/plugins/tpm

- name: Install tmux plugins
  shell: /home/{{ username }}/.config/tmux/plugins/tpm/bin/install_plugins
  args:
    chdir: /home/{{ username }}
  become: true
  become_user: {{ username }}

- name: Refresh home directory ownership
  file:
    path: "/home/{{ username }}/"
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"