---
- name: Ensure mount base directory exists
  ansible.builtin.file:
    path: "{{ mount_base }}"
    state: directory
    mode: '0755'
  become: yes

- name: Create mount points with correct permissions for TEST user
  ansible.builtin.file:
    path: "{{ mount_base }}/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop: "{{ mount_points }}"
  become: yes

- name: Check if NFS server is reachable
  ansible.builtin.wait_for:
    host: "{{ nfs_server }}"
    port: 2049
    timeout: 5
  ignore_errors: yes
  register: nfs_server_check

- name: Debug mount point paths
  ansible.builtin.debug:
    msg: "Mount point path: {{ mount_base }}/{{ item }}"
  loop: "{{ mount_points }}"

- name: Mount NFS4 shares
  ansible.builtin.command:
    cmd: "mount -t nfs4 -o {{ nfs_mount_opts }} {{ nfs_server }}:{{ mount_base }}/{{ item }} {{ mount_base }}/{{ item }}"
  loop: "{{ mount_points }}"
  become: yes
  when: nfs_server_check is succeeded
  register: mount_result
  ignore_errors: yes
  changed_when: mount_result.rc == 0

- name: Add NFS mounts to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "{{ nfs_server }}:{{ mount_base }}/{{ item }} {{ mount_base }}/{{ item }} nfs4 {{ nfs_mount_opts }} 0 0"
    regexp: "^{{ nfs_server }}:{{ mount_base }}/{{ item }} {{ mount_base }}/{{ item }}"
  loop: "{{ mount_points }}"
  become: yes
  when: nfs_server_check is succeeded