---
- name: Ensure mount base directory exists
  ansible.builtin.file:
    path: "{{ mount_base }}"
    state: directory
    mode: '0755'

- name: Create mount points with correct permissions for TEST user
  ansible.builtin.file:
    path: "{{ mount_base }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
  loop: "{{ mount_points }}"

- name: Check if NFS server is reachable
  ansible.builtin.wait_for:
    host: "{{ nfs_server }}"
    port: 2049
    timeout: 5
  ignore_errors: yes
  register: nfs_server_check

- name: Mount NFS4 shares and ensure they are persistent
  ansible.builtin.mount:
    path: "{{ mount_base }}/{{ item }}"
    src: "{{ nfs_server }}:{{ mount_base }}/{{ item }}"
    fstype: nfs4
    opts: "{{ nfs_mount_opts }}"
    state: mounted
    fstab: yes
  loop: "{{ mount_points }}"
  when: nfs_server_check is succeeded
  register: mount_result
  ignore_errors: yes

- name: Display mount errors if any
  ansible.builtin.debug:
    msg: "Failed to mount {{ item.item }}. Error: {{ item.msg }}"
  loop: "{{ mount_result.results }}"
  when: mount_result is failed and item is failed