---
- name: Create mount points
  ansible.builtin.file:
    path: "{{ mount_base }}/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop: "{{ mount_points }}"

- name: Mount NFS4 shares and ensure they are persistent
  ansible.builtin.mount:
    path: "{{ mount_base }}/{{ item }}"
    src: "{{ nfs_server }}:{{ mount_base }}/{{ item }}"
    fstype: nfs4
    opts: "{{ nfs_mount_opts }}"
    state: mounted
    fstab: yes
  loop: "{{ mount_points }}"