---
- name: Set Git user name
  ansible.builtin.command:
    cmd: git config --global user.name "{{ github_username }}"

- name: Set Git user email
  ansible.builtin.command:
    cmd: git config --global user.email "{{ github_mail }}"

- name: Clone Git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    update: yes
  with_items: "{{ git_repositories }}"