- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - git
      - ca-certificates
      - software-properties-common
      - curl
      - btop
      - iotop
      - lsof
      - ncdu
      - neofetch
      - net-tools
      - nmap
      - rsync
      - sshfs
      - tmux
      - traceroute
      - wget
      - whois
      - zsh
      - jq
      - python3
      - python3-pip
      - nfs-kernel-server
      - nfs-common
      - fontconfig
      - unzip
      - bat                 # https://github.com/sharkdp/bat
      - fzf                 # https://github.com/junegunn/fzf
#      - exa                 # https://the.exa.website/introduction