---
- name: Initial setup of Ubuntu server
  hosts: server
  vars_files:
    - ../variables/global.yml
  #become: yes
  #become_user: "{{ username }}"
  tasks:
    - block:
        - include_tasks: tasks/system/update-upgrade.yml
        - include_tasks: tasks/packages/install-common-packages.yml
        - include_tasks: tasks/git/clone-git-repos.yml
        - include_tasks: tasks/system/create-server-home-dirs.yml
        - include_tasks: tasks/docker/install-docker.yml
        - include_tasks: tasks/zsh/install-oh-my-zsh.yml
        - include_tasks: tasks/dotfiles/chezmoi-dotfiles.yml
      become: yes
      become_user: "{{ username }}"